fix mysql connect port mistake.
colin-han/p2m-message-server pull request #11
Opened 2020-10-20 01:51 UTC by yolandaYanYu

2020-10-20 03:56 UTC, colin-han requested changes

2020-10-20 03:56 UTC, colin-han commented on package.json
> +  "version": "2.2.0",
version should be 2.1.10.

2020-10-20 06:49 UTC, colin-han requested changes

2020-10-20 06:49 UTC, colin-han commented on tools/validateConfig.js
> +r = validate('database', 'port', 'DB_PORT', 'string') && r;
这个参数不应该是number吗？

2020-10-20 06:52 UTC, yolandaYanYu commented on tools/validateConfig.js
> +r = validate('database', 'port', 'DB_PORT', 'string') && r;
写number的时候报错，服务启动不起来，错误显示应该是string

2020-10-20 07:26 UTC, colin-han commented on tools/validateConfig.js
> +r = validate('database', 'port', 'DB_PORT', 'string') && r;
那是因为你引号少些了半个吧？

2020-10-20 09:11 UTC, yolandaYanYu commented on tools/validateConfig.js
> +r = validate('database', 'port', 'DB_PORT', 'string') && r;
引号少半个报的错是语法错误，加上引号之后报的是类型错误，两个错误不一样

2020-10-21 02:39 UTC, colin-han commented
Close this PR, because  I had remove validateConfig step by myself.

2020-10-21 02:39 UTC, closed without merging